version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/myapp
hooks:
  BeforeInstall:
    - location: Scripts/UnzipResourceBundle.sh
      timeout: 100
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 100
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 100
      runas: root
  