version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/myapp
permissions:
  - object: /home/ubuntu/
    owner: root
    group: root
    mode: 777
hooks:
  BeforeInstall:
    - location: scripts/unzipBundle.sh
      timeout: 400
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 400
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 400
      runas: root
  